# Generated by Django 5.2.7 on 2025-11-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aianalysis',
            old_name='analyzed_at',
            new_name='processed_at',
        ),
        migrations.RemoveField(
            model_name='monitoringlog',
            name='message',
        ),
        migrations.RemoveField(
            model_name='monitoringlog',
            name='status',
        ),
        migrations.AddField(
            model_name='monitoringlog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monitoringlog',
            name='result',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('no_new_tweets', 'No New Tweets')], default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='tweet',
            name='ai_analyzed',
            field=models.BooleanField(default=False, help_text='是否已进行AI分析'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='ai_relevant',
            field=models.BooleanField(default=False, help_text='AI判断是否相关'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI生成的摘要'),
        ),
        migrations.AddField(
            model_name='xaccount',
            name='ai_filter_enabled',
            field=models.BooleanField(default=False, help_text='智能推荐开关'),
        ),
        migrations.AddField(
            model_name='xaccount',
            name='fetch_from_date',
            field=models.DateField(blank=True, help_text='开始拉取推文的日期', null=True),
        ),
        migrations.AddField(
            model_name='xaccount',
            name='fetch_to_date',
            field=models.DateField(blank=True, help_text='结束拉取推文的日期', null=True),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='importance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='monitoringlog',
            name='execution_time',
            field=models.FloatField(help_text='Execution time in seconds'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.CharField(choices=[('new_tweet', 'New Tweet'), ('important_tweet', 'Important Tweet'), ('error', 'Error')], max_length=20),
        ),
    ]
