# Generated by Django 5.2.7 on 2025-11-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_monitor', '0003_recommendedtweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xaccount',
            name='avatar_url',
            field=models.URLField(blank=True, default='https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.png', null=True),
        ),
    ]
