# Generated by Django 5.0.6 on 2025-11-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_monitor', '0004_alter_xaccount_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='xaccount',
            name='monitoring_interval',
            field=models.IntegerField(choices=[(30, '每30分钟'), (60, '每1小时'), (240, '每4小时'), (720, '每12小时')], default=240, help_text='监控间隔（分钟）'),
        ),
    ]
