# Generated by Django 5.0.6 on 2025-11-09 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_monitor', '0005_xaccount_monitoring_interval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='规则名称', max_length=255)),
                ('prompt', models.TextField(help_text='AI筛选提示词')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_applied', models.DateTimeField(blank=True, help_text='最后应用时间', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prompt_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='recommendedtweet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recommendedtweet',
            name='prompt_rule',
            field=models.ForeignKey(blank=True, help_text='使用的推荐规则', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_tweets', to='x_monitor.aipromptrule'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendedtweet',
            unique_together={('user', 'tweet', 'prompt_rule')},
        ),
    ]
