# Generated by Django 5.0.6 on 2025-11-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x_monitor', '0006_aipromptrule_alter_recommendedtweet_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipromptrule',
            name='target_accounts',
            field=models.ManyToManyField(blank=True, help_text='应用此规则的Twitter账号（为空表示应用到所有账号）', related_name='ai_rules', to='x_monitor.xaccount'),
        ),
    ]
