# Cloud Build 最低配置 - 极限成本优化
# 月成本预估: $15-25 (比标准配置节省 80%)

steps:
  # Build backend Docker image (使用缓存加速构建)
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--cache-from"
      - "gcr.io/$PROJECT_ID/auto-ski-info-backend:latest"
      - "-t"
      - "gcr.io/$PROJECT_ID/auto-ski-info-backend:$BUILD_ID"
      - "-t"
      - "gcr.io/$PROJECT_ID/auto-ski-info-backend:latest"
      - "-f"
      - "backend/Dockerfile"
      - "backend"

  # Build frontend Docker image (使用缓存加速构建)
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--cache-from"
      - "gcr.io/$PROJECT_ID/auto-ski-info-frontend:latest"
      - "-t"
      - "gcr.io/$PROJECT_ID/auto-ski-info-frontend:$BUILD_ID"
      - "-t"
      - "gcr.io/$PROJECT_ID/auto-ski-info-frontend:latest"
      - "-f"
      - "frontend/Dockerfile"
      - "frontend"

  # Push images (并行推送会在后台进行)
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/auto-ski-info-backend:$BUILD_ID"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/auto-ski-info-frontend:$BUILD_ID"

  # Deploy backend to Cloud Run - 最低配置
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "auto-ski-info-backend"
      - "--image"
      - "gcr.io/$PROJECT_ID/auto-ski-info-backend:$BUILD_ID"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8000"
      # 最低资源配置
      - "--memory"
      - "512Mi" # 从 2Gi 降至 512Mi (节省 75%)
      - "--cpu"
      - "1" # 从 2 降至 1 (节省 50%)
      - "--concurrency"
      - "80" # 提高并发处理能力
      - "--min-instances"
      - "0" # 无流量时缩减到 0 (节省 100% 空闲成本)
      - "--max-instances"
      - "3" # 从 10 降至 3 (限制最大成本)
      - "--timeout"
      - "300"
      - "--cpu-throttling" # 空闲时 CPU 节流
      - "--cpu-boost" # 启动时 CPU 加速
      # 环境变量
      - "--set-env-vars"
      - "USE_CLOUD_SQL=True,CLOUD_DB_NAME=ski-scrapy,CLOUD_DB_USER=postgres,DEBUG=False,ALLOWED_HOSTS=*"
      # Secret Manager
      - "--set-secrets"
      - "DATABASE_PASSWORD=DATABASE_PASSWORD:latest,AI_API_KEY_GOOGLE=AI_API_KEY_GOOGLE:latest,X_API_KEY=X_API_KEY:latest,X_API_SECRET=X_API_SECRET:latest,X_ACCESS_TOKEN=X_ACCESS_TOKEN:latest,X_ACCESS_TOKEN_SECRET=X_ACCESS_TOKEN_SECRET:latest,X_BEARER_TOKEN=X_BEARER_TOKEN:latest"
      # Cloud SQL 连接
      - "--add-cloudsql-instances"
      - "gen-lang-client-0543160602:asia-northeast1:ai-project-database"

  # Deploy frontend to Cloud Run - 最低配置
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "auto-ski-info-frontend"
      - "--image"
      - "gcr.io/$PROJECT_ID/auto-ski-info-frontend:$BUILD_ID"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "80"
      # 最低资源配置
      - "--memory"
      - "256Mi" # 从 512Mi 降至 256Mi (节省 50%)
      - "--cpu"
      - "0.5" # 使用半个 CPU (节省 50%)
      - "--concurrency"
      - "80"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "2" # 从 5 降至 2
      - "--cpu-throttling"
      # 环境变量 - 使用占位符，部署后手动更新
      - "--set-env-vars"
      - "REACT_APP_API_URL=https://auto-ski-info-backend-asia-northeast1-replaceme.a.run.app/api"

  # 手动创建 Cloud Scheduler (首次部署后执行，不在 Cloud Build 中)
  # 使用智能分级调度节省成本
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "⚠️  注意: Cloud Scheduler 需要手动创建以节省成本"
        echo "使用智能分级调度，请参考 SMART_SCHEDULING_DEPLOYMENT.md"
        echo ""
        echo "快速创建 30 分钟间隔的基本调度器:"
        echo "gcloud scheduler jobs create http monitor-x-accounts-30min \\"
        echo "  --schedule=\"*/30 * * * *\" \\"
        echo "  --uri=\"https://auto-ski-info-backend-asia-northeast1-xxxx.a.run.app/api/monitor/trigger-monitoring/?interval=30\" \\"
        echo "  --http-method=POST \\"
        echo "  --location=asia-northeast1 \\"
        echo "  --time-zone=Asia/Tokyo"

images:
  - "gcr.io/$PROJECT_ID/auto-ski-info-backend:$BUILD_ID"
  - "gcr.io/$PROJECT_ID/auto-ski-info-backend:latest"
  - "gcr.io/$PROJECT_ID/auto-ski-info-frontend:$BUILD_ID"
  - "gcr.io/$PROJECT_ID/auto-ski-info-frontend:latest"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_4" # 从 E2_HIGHCPU_8 降至 E2_HIGHCPU_4 (节省 50%)
  substitution_option: "ALLOW_LOOSE"
  diskSizeGb: 100 # 默认值，足够使用

# 成本优化总结:
# - Build Machine: E2_HIGHCPU_8 → E2_HIGHCPU_4 (-50%)
# - Backend: 2Gi/2CPU → 512Mi/1CPU (-75% memory, -50% CPU)
# - Frontend: 512Mi/1CPU → 256Mi/0.5CPU (-50% memory, -50% CPU)
# - Concurrency: 提高到 80 (减少实例数)
# - Max Instances: Backend 10→3, Frontend 5→2
# - CPU Throttling + Boost: 优化空闲和启动性能
# - Docker Cache: 加速构建，减少构建时间
#
# 预估月成本: $15-25 (vs 标准配置 $80-130)
# 节省: 80-85%
