steps:
  # Build backend Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/auto-ski-info-backend:$BUILD_ID"
      - "-t"
      - "gcr.io/$PROJECT_ID/auto-ski-info-backend:latest"
      - "-f"
      - "backend/Dockerfile"
      - "backend"

  # Build frontend Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/auto-ski-info-frontend:$BUILD_ID"
      - "-t"
      - "gcr.io/$PROJECT_ID/auto-ski-info-frontend:latest"
      - "-f"
      - "frontend/Dockerfile"
      - "frontend"

  # Push backend image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/auto-ski-info-backend:$BUILD_ID"

  # Push frontend image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/auto-ski-info-frontend:$BUILD_ID"

  # Deploy backend to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "auto-ski-info-backend"
      - "--image"
      - "gcr.io/$PROJECT_ID/auto-ski-info-backend:$BUILD_ID"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8000"
      - "--memory"
      - "2Gi"
      - "--cpu"
      - "2"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "10"
      - "--timeout"
      - "300"
      # 環境変数設定
      - "--set-env-vars"
      - "USE_CLOUD_SQL=True,CLOUD_DB_NAME=ski-scrapy,CLOUD_DB_USER=postgres,DEBUG=False,ALLOWED_HOSTS=*"
      # Secret Manager から API キーとパスワードを取得
      - "--set-secrets"
      - "DATABASE_PASSWORD=DATABASE_PASSWORD:latest,AI_API_KEY_GOOGLE=AI_API_KEY_GOOGLE:latest,X_API_KEY=X_API_KEY:latest,X_API_SECRET=X_API_SECRET:latest,X_ACCESS_TOKEN=X_ACCESS_TOKEN:latest,X_ACCESS_TOKEN_SECRET=X_ACCESS_TOKEN_SECRET:latest,X_BEARER_TOKEN=X_BEARER_TOKEN:latest"
      # Cloud SQL 接続
      - "--add-cloudsql-instances"
      - "gen-lang-client-0543160602:asia-northeast1:ai-project-database"

  # Deploy frontend to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "auto-ski-info-frontend"
      - "--image"
      - "gcr.io/$PROJECT_ID/auto-ski-info-frontend:$BUILD_ID"
      - "--region"
      - "asia-northeast1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "80"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "5"
      # フロントエンドの環境変数
      - "--set-env-vars"
      - "REACT_APP_API_URL=https://auto-ski-info-backend-${_REGION_ID}.a.run.app/api"

  # Cloud Scheduler でバックグラウンドタスクを実行 (Celery の代替)
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # 15分ごとに監視タスクを実行する Cloud Scheduler ジョブを作成/更新
        gcloud scheduler jobs create http monitor-x-accounts \
          --schedule="*/15 * * * *" \
          --uri="https://auto-ski-info-backend-${_REGION_ID}.a.run.app/api/monitor/trigger-monitoring/" \
          --http-method=POST \
          --oidc-service-account-email=$_SERVICE_ACCOUNT \
          --location=asia-northeast1 \
          --time-zone=Asia/Tokyo \
          || gcloud scheduler jobs update http monitor-x-accounts \
          --schedule="*/15 * * * *" \
          --uri="https://auto-ski-info-backend-${_REGION_ID}.a.run.app/api/monitor/trigger-monitoring/" \
          --location=asia-northeast1

images:
  - "gcr.io/$PROJECT_ID/auto-ski-info-backend:$BUILD_ID"
  - "gcr.io/$PROJECT_ID/auto-ski-info-backend:latest"
  - "gcr.io/$PROJECT_ID/auto-ski-info-frontend:$BUILD_ID"
  - "gcr.io/$PROJECT_ID/auto-ski-info-frontend:latest"

# 置換変数（デフォルト値）
substitutions:
  _REGION_ID: "asia-northeast1"
  _SERVICE_ACCOUNT: "default-service-account@${PROJECT_ID}.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
  substitution_option: "ALLOW_LOOSE"
